name: Build and Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Version number for the release (e.g., v1.0.0)"
        required: true
        type: string
      release_notes:
        description: "Release notes"
        required: true
        type: string

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i
      - run: npm i -g "@yao-pkg/pkg"
      - run: node scripts/build.js win
      - name: Rename Windows executable
        shell: pwsh
        run: |
          $version = "${{ github.event.inputs.version }}" -replace '^v',''
          Rename-Item "./executables/manga-devourer-server.exe" "./executables/manga-devourer-server-win-$version.exe"
      - name: Upload Windows artifact
        uses: actions/upload-artifact@v4
        with:
          name: win-executable
          path: executables/manga-devourer-server-win-*.exe
          retention-days: 1

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i
      - run: npm i -g "@yao-pkg/pkg"
      - run: node scripts/build.js linux
      - name: Rename Linux executable
        run: |
          version="${{ github.event.inputs.version }}"
          version=${version#v}
          mv "./executables/manga-devourer-server" "./executables/manga-devourer-server-linux-${version}"
      - name: Upload Linux artifact
        uses: actions/upload-artifact@v4
        with:
          name: linux-executable
          path: executables/manga-devourer-server-linux-*
          retention-days: 1

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - run: npm i
      - run: npm i -g "@yao-pkg/pkg"
      - run: node scripts/build.js macos
      - name: Rename macOS executable
        run: |
          version="${{ github.event.inputs.version }}"
          version=${version#v}
          mv "./executables/manga-devourer-server" "./executables/manga-devourer-server-macos-${version}"
      - name: Upload macOS artifact
        uses: actions/upload-artifact@v4
        with:
          name: macos-executable
          path: executables/manga-devourer-server-macos-*
          retention-days: 1

  create-release:
    needs: [build-windows, build-linux, build-macos]
    runs-on: ubuntu-latest
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: Release ${{ github.event.inputs.version }}
          body: ${{ github.event.inputs.release_notes }}
          files: |
            artifacts/win-executable/manga-devourer-server-win-${{ github.event.inputs.version }}.exe
            artifacts/linux-executable/manga-devourer-server-linux-${{ github.event.inputs.version }}
            artifacts/macos-executable/manga-devourer-server-macos-${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
